// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafetyOps.Api.Data;

#nullable disable

namespace SafetyOps.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927194257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SafetyOps.Api.Domain.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ELV-001",
                            Title = "Electrical - Low Voltage"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ELH-001",
                            Title = "Electrical - High Voltage"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ELS-001",
                            Title = "Electrical - Safety Basics"
                        },
                        new
                        {
                            Id = 4,
                            Code = "FPS-001",
                            Title = "Fire Prevention and Safety"
                        },
                        new
                        {
                            Id = 5,
                            Code = "HAZ-001",
                            Title = "Hazardous Materials Handling"
                        },
                        new
                        {
                            Id = 6,
                            Code = "PPE-001",
                            Title = "Personal Protective Equipment"
                        },
                        new
                        {
                            Id = 7,
                            Code = "FAC-001",
                            Title = "First Aid and CPR"
                        },
                        new
                        {
                            Id = 8,
                            Code = "LOT-001",
                            Title = "Lockout/Tagout Procedures"
                        });
                });

            modelBuilder.Entity("SafetyOps.Api.Domain.MedicalAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("MedicalAppointments");
                });

            modelBuilder.Entity("SafetyOps.Api.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subscription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SafetyOps.Api.Domain.Stressor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Stressors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "STR-001",
                            Name = "Solvent Exposure"
                        },
                        new
                        {
                            Id = 2,
                            Code = "STR-002",
                            Name = "Noise Exposure"
                        },
                        new
                        {
                            Id = 3,
                            Code = "STR-003",
                            Name = "Dust Inhalation"
                        });
                });

            modelBuilder.Entity("SafetyOps.Api.Domain.TrainingClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ClassDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "ClassDate");

                    b.ToTable("TrainingClasses");
                });

            modelBuilder.Entity("SafetyOps.Api.Domain.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ExamTypeOptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WT-001",
                            ExamTypeOptions = "[\"Initial\",\"Periodic\",\"Exit\",\"Return to Duty\"]",
                            Name = "Chemical Exposure - Solvents"
                        },
                        new
                        {
                            Id = 2,
                            Code = "WT-002",
                            ExamTypeOptions = "[\"Initial\",\"Periodic\",\"Exit\"]",
                            Name = "Noise Hazard - Industrial"
                        },
                        new
                        {
                            Id = 3,
                            Code = "WT-003",
                            ExamTypeOptions = "[\"Initial\",\"Periodic\",\"Exit\",\"Special\"]",
                            Name = "Respiratory Hazard - Dust"
                        });
                });

            modelBuilder.Entity("WorkTaskStressor", b =>
                {
                    b.Property<int>("WorkTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StressorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkTaskId", "StressorId");

                    b.HasIndex("StressorId");

                    b.ToTable("WorkTaskStressor");

                    b.HasData(
                        new
                        {
                            WorkTaskId = 1,
                            StressorId = 1
                        },
                        new
                        {
                            WorkTaskId = 2,
                            StressorId = 2
                        },
                        new
                        {
                            WorkTaskId = 3,
                            StressorId = 3
                        });
                });

            modelBuilder.Entity("SafetyOps.Api.Domain.MedicalAppointment", b =>
                {
                    b.HasOne("SafetyOps.Api.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("SafetyOps.Api.Domain.AppointmentStressor", "Stressors", b1 =>
                        {
                            b1.Property<int>("AppointmentId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("StressorId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ExamType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("AppointmentId", "StressorId");

                            b1.HasIndex("StressorId");

                            b1.ToTable("AppointmentStressors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");

                            b1.HasOne("SafetyOps.Api.Domain.Stressor", "Stressor")
                                .WithMany()
                                .HasForeignKey("StressorId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("Stressor");
                        });

                    b.Navigation("Person");

                    b.Navigation("Stressors");
                });

            modelBuilder.Entity("SafetyOps.Api.Domain.TrainingClass", b =>
                {
                    b.HasOne("SafetyOps.Api.Domain.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("WorkTaskStressor", b =>
                {
                    b.HasOne("SafetyOps.Api.Domain.Stressor", null)
                        .WithMany()
                        .HasForeignKey("StressorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafetyOps.Api.Domain.WorkTask", null)
                        .WithMany()
                        .HasForeignKey("WorkTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
